"""The frozen champion: BTC_FLOOR_050_CONTROL.

Every experiment in the second edge-improvement phase is measured against this
and nothing else. It is a module rather than a JSON blob so that a candidate
cannot quietly drift the control underneath itself: the definition lives in
version control, the numbers are regenerated from it, and a test pins both.

Nothing here may be edited to make a later result look better. If the control
ever needs to change, it becomes a *new* control with a new name and every
comparison is re-run against it.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Dict, Sequence

#: The accepted configuration from the first edge-improvement phase.
#: `trend_floor` is the only deviation from the repository defaults; everything
#: else is whatever the walk-forward search is free to choose within
#: DEFAULT_SEARCH_SPACE.
CONTROL_NAME = "BTC_FLOOR_050_CONTROL"

CONTROL_OVERRIDES: Dict[str, Sequence] = {"trend_floor": [0.50]}

CONTROL_SPEC = {
    "name": CONTROL_NAME,
    "symbol": "BTC-USD",
    "interval": "1d",
    "source": "coinbase",
    "data_start": "2015-01-01",
    "traded_start": "2017-07-29",
    "traded_end": "2026-09-12",
    "periods_per_year": 365.0,
    "initial_capital": 100.0,
    "cost_scenario": "BASE (15 bps per side: 10 fee + 2.5 half-spread + 2.5 slippage)",
    "execution": "decision at close of bar t, fill at open of bar t+1",
    "search_space_size": 2304,
    "candidates_per_fold": 64,
    "seeds": (0, 1, 2, 3, 4, 5),
    "overrides": dict(CONTROL_OVERRIDES),
    "safety": (
        "long-only by selection (allow_short=0 in 100% of folds); gross capped by "
        "max_leverage; no live trading; paper interlocks untouched"
    ),
}

#: Measured on the six control seeds. Regenerated by scripts_edge2_control.py;
#: the test suite checks the regenerated numbers still match these.
CONTROL_METRICS = {
    "median_final_equity": 2475.29,
    "mean_final_equity": 2507.88,
    "min_final_equity": 1995.21,
    "max_final_equity": 3141.41,
    "median_cagr": 0.421,
    "median_sharpe": 1.088,
    "median_sortino": 1.443,
    "median_max_drawdown": -0.470,
    "median_avg_exposure": 0.545,
    "seed0_final_equity": 2479.37,
    "seed0_sharpe": 1.089,
    "seed0_trades": 711,
}


def describe() -> str:
    lines = [f"== {CONTROL_NAME} ==", ""]
    for k, v in CONTROL_SPEC.items():
        lines.append(f"  {k:<20} {v}")
    lines.append("")
    for k, v in CONTROL_METRICS.items():
        lines.append(f"  {k:<26} {v}")
    return "\n".join(lines)
